from jflow.jfsite.global_settings import *

DEBUG = False
TEMPLATE_DEBUG = DEBUG
SEND_BROKEN_LINK_EMAILS = True

CACHE_BACKEND      = 'memcached://localhost:11211/'
DEFAULT_BACKEND    = 'redis://127.0.0.1:6379/?db=1'


# EMAILS
#EMAIL_HOST             = PSETTINGS.id.EMAIL_HOST
#EMAIL_PORT             = PSETTINGS.id.EMAIL_PORT
#EMAIL_SUBJECT_PREFIX   = PSETTINGS.id.EMAIL_SUBJECT_PREFIX
#EMAIL_HOST_USER        = PSETTINGS.id.EMAIL_HOST_USER
#EMAIL_HOST_PASSWORD    = PSETTINGS.id.EMAIL_HOST_PASSWORD
#EMAIL_USE_TLS          = PSETTINGS.id.EMAIL_USE_TLS
#DEFAULT_FROM_EMAIL     = PSETTINGS.id.DEFAULT_FROM_EMAIL